apiVersion: apps/v1
kind: Deployment
metadata:
  name: completetest
  namespace: testbus
  labels:
    app: completetest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: completetest
  template:
    metadata:
      labels:
        app: completetest
    spec:
      containers:
        - name: testbus
          image: jieshe/testbus:latest
          imagePullPolicy: Always
          command: ["testbus"]
          args: [
            "complete",
            "--conn-str=$(SERVICEBUS_CONNECTION_STRING)"
          ]
          env:
            - name: SERVICEBUS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: testbus-secret
                  key: connStr
