apiVersion: batch/v1
kind: Job
metadata:
  name: loadmultipletest
  namespace: testbus
  labels:
    app: loadmultipletest
spec:
  template:
    metadata:
      labels:
        app: loadmultipletest
    spec:
      containers:
      - name: testbus
        image: jieshe/testbus:latest
        imagePullPolicy: Always
        command: ["testbus"]
        args: [
          "load-multiple",
          "--conn-str=$(SERVICEBUS_CONNECTION_STRING)"
        ]
        env:
          - name: SERVICEBUS_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: testbus-secret
                key: connStr
      restartPolicy: Never
  backoffLimit: 1
