apiVersion: batch/v1
kind: Job
metadata:
  name: sparsetest
  namespace: testbus
  labels:
    app: sparsetest
spec:
  template:
    metadata:
      labels:
        app: sparsetest
    spec:
      containers:
        - name: testbus
          image: jieshe/testbus:latest
          imagePullPolicy: Always
          command: ["testbus"]
          args: [
            "sparse-test",
            "--conn-str=$(SERVICEBUS_CONNECTION_STRING)"
          ]
          env:
            - name: SERVICEBUS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: testbus-secret
                  key: connStr
      restartPolicy: Never
  backoffLimit: 1
